## Switches
set_property PACKAGE_PIN V17 [get_ports {SW1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW1}]
set_property PACKAGE_PIN V16 [get_ports {SW2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW2}]
set_property PACKAGE_PIN W16 [get_ports {SW3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW3}]
set_property PACKAGE_PIN W17 [get_ports {SW4}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW4}]
set_property PACKAGE_PIN W15 [get_ports {SW5}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW5}]
set_property PACKAGE_PIN V15 [get_ports {SW6}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW6}]
set_property PACKAGE_PIN W14 [get_ports {SW7}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW7}]
set_property PACKAGE_PIN W13 [get_ports {SW8}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW8}]
set_property PACKAGE_PIN V2 [get_ports {SW9}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW9}]
set_property PACKAGE_PIN T3 [get_ports {SW10}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW10}]
 
## LEDs
set_property PACKAGE_PIN U16 [get_ports {LED1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED1}]
set_property PACKAGE_PIN E19 [get_ports {LED2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED2}]
set_property PACKAGE_PIN U19 [get_ports {LED3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED3}]
set_property PACKAGE_PIN V19 [get_ports {LED4}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED4}]
set_property PACKAGE_PIN W18 [get_ports {LED5}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED5}]
set_property PACKAGE_PIN U15 [get_ports {LED6}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED6}]
set_property PACKAGE_PIN U14 [get_ports {LED7}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED7}]
set_property PACKAGE_PIN V14 [get_ports {LED8}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED8}]
set_property PACKAGE_PIN V13 [get_ports {LED9}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED9}]
set_property PACKAGE_PIN V3 [get_ports {LED10}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED10}]
	
##7 segment display
set_property PACKAGE_PIN W7 [get_ports {SEG0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG0}]
set_property PACKAGE_PIN W6 [get_ports {SEG1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG1}]
set_property PACKAGE_PIN U8 [get_ports {SEG2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG2}]
set_property PACKAGE_PIN V8 [get_ports {SEG3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG3}]
set_property PACKAGE_PIN U5 [get_ports {SEG4}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG4}]
set_property PACKAGE_PIN V5 [get_ports {SEG5}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG5}]
set_property PACKAGE_PIN U7 [get_ports {SEG6}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG6}]

set_property PACKAGE_PIN V7 [get_ports DP]							
    set_property IOSTANDARD LVCMOS33 [get_ports DP]

set_property PACKAGE_PIN U2 [get_ports {AN0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AN0}]
set_property PACKAGE_PIN U4 [get_ports {AN1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AN1}]
set_property PACKAGE_PIN V4 [get_ports {AN2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AN2}]
set_property PACKAGE_PIN W4 [get_ports {AN3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AN3}]